### PR TITLE
Install julia with conda

### PR DESCRIPTION
**Pull request by rodluger**
The build fails locally for me because I don't have julia installed. Feel free to edit the version number if needed.

### CODE REVIEW

**Comment by rodluger** [comment]
I'm now getting issues with certain packages not being registered. @palumbom Any idea how to fix this? 
image

**Comment by palumbom** [comment]
Julia 1.8 works! Good catch. 

As for the package issues, I'm genuinely not sure why it's saying they're not registered. RvSpectML is indeed on the JuliaRegistry, and so Pkg.instantiate() shouldn't have an issue seeing and installing it. 

I'm guessing you:
1) cloned the repo,
2) added the Julia 1.8 requirement in environment.yml,
3) ran ```showyourwork build``` 

and then it died when it tried installing the Julia package dependencies?

**Comment by rodluger** [comment]
It dies while trying to run `fig4_sim.jl`, specifically when doing 

```julia
Pkg.activate("."); Pkg.instantiate()"
```

I found a bunch of SO posts saying updating the registry (`[up` or, I'm assuming, `Pkg.update()`) could help, but that led to a similar LoadError for a different package. I don't code in julia so I'm a bit at a loss about what all those errors mean. Any ideas?

**Comment by palumbom** [comment]
I'm confused too, since the Manifest should have already have all the resolved dependencies and be able to exactly reproduce the package environment. So as far as I understand ```Pkg.update()``` shouldn't be necessary. I'm going to try cloning and running this on a computer that doesn't have Julia already installed, and see if I can troubleshoot that way. I'll go ahead and merge this pull request so it has the Julia 1.8 dep in environment.yml, first.

**Comment by palumbom** [comment]
Ok! So I was able to clone the repo on a non-Julia'd machine and generate Figures 1-3 (but not 4-7 without some trickery, because of the caching issues unrelated to the Julia environment stuff described here). 

I re-resolved the Manifest on my machine, and added some extra lines to the top of the figx_plot.jl that point PyCall.jl to the condo env that showyourwork creates. Hopefully the combo of those two changes fixes the issue for you. If you have a chance would you mind re-cloning/pulling and building the manuscript again? If you want to trick showyourwork into producing 4-7, I've also attached the necessary input files here: https://pennstateoffice365-my.sharepoint.com/:f:/g/personal/mlp95_psu_edu/EsXdo0BBvcpJsvePrIl9_1MBpCFiqNJEjCCyhnoo9VHFFg?e=YDoRbj 

The timestamps for those will be newer than the latest commits for figx_sim.jl, so showyourwork should be happy to use them to build the manuscript locally. 

(Sorry, GitHub won't let me attach .jld2 format files)

**Comment by rodluger** [comment]
@palumbom I re-cloned the package, ran `showyourwork`, and got the exact same error. But then I did it a few more times and got three or four different errors; a couple related to `PyCall` not building correctly, one complaining about the file "~/.julia/packages/GRASS/KYFPP/figures/fig_functions.jl" not existing, and a few others I didn't keep track of. So there are still issues. One potential source of issues is that `julia` doesn't seem to be properly containerized -- the fact that it's searching for a file in the user's home directory means you can potentially get hysteresis across builds even after running `showyourwork clean`. 

I'm afraid I don't have any more time this week to tinker with this. I would recommend debugging via GitHub Actions once you get the caching stuff working (or, if you don't get it to work, bypassing it by placing the problematic figures in the `static` directory for now, for instance).

I suspect you'll run into some or all of these errors in GitHub Actions, which might make it easier for you to debug rather than relying on the back-and-forth with me.

But do keep me posted -- I should have some time next week to think about this.

**Comment by palumbom** [comment]
@rodluger Thanks for the suggestions! I'll keep tinkering on GitHub actions and keep you posted. Again, I super appreciate you helping me deal with this very specific use case (on top of the dealing with Julia shenanigans)!

**Pull request merged**
